name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        default: true
        toolchain: stable
    - name: Run cargo fmt
      run: |
        cargo fmt --all -- --check

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          - linux
          - macos
          - windows
        include:
          - build: linux
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-11
            target: x86_64-apple-darwin
          - build: windows
            os: windows-2019
            target: i686-pc-windows-msvc

    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: stable
      - name: Cargo Cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
